# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 361c0577a479882f25ab06ca5664c72b26e4ba61274e39a793f8905cda3178ac56700a46aa955d3258ad864712054ec109e66377e67be831facf251f4bf4dfcf

test:
  secret_key_base: 6af9c7dde214c1efca567f8ea42e886dd2ef92039ada92f73942c797c9ac33bafbe21b0a82dc31594deb87c9552485e78ec36c66e10b3f7ecc1211a2a63cd6d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
